services:
  ccm:
    image: ghcr.io/loganjanssen/ccm:latest
    container_name: ccm
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /etc/ccm:/etc/ccm:ro
      - ${HOME}/.ssh:/home/ccm/.ssh:ro
    environment:
      - CCM_SSH_KEY=/home/ccm/.ssh/id_ed25519
